In [13]:
import numpy as np
import pandas as pd
import glob as gl
from pprint import pprint

fname = 'diagnosis-of-covid-19-and-its-clinical-spectrum.csv'
path = gl.glob(f'../**/**/{fname}')
df = pd.read_csv(path[0])

see = pd.DataFrame(len(df) - df.isna().sum(), index=df.columns, columns=['Non-NaN']).head(100)

#for index, row in see.iterrows():
#    print(row)

Non-NaN    5644
Name: patient_id, dtype: int64
Non-NaN    5644
Name: patient_age_quantile, dtype: int64
Non-NaN    5644
Name: sars_cov_2_exam_result, dtype: int64
Non-NaN    5644
Name: patient_addmited_to_regular_ward_1_yes_0_no, dtype: int64
Non-NaN    5644
Name: patient_addmited_to_semi_intensive_unit_1_yes_0_no, dtype: int64
Non-NaN    5644
Name: patient_addmited_to_intensive_care_unit_1_yes_0_no, dtype: int64
Non-NaN    603
Name: hematocrit, dtype: int64
Non-NaN    603
Name: hemoglobin, dtype: int64
Non-NaN    602
Name: platelets, dtype: int64
Non-NaN    599
Name: mean_platelet_volume, dtype: int64
Non-NaN    602
Name: red_blood_cells, dtype: int64
Non-NaN    602
Name: lymphocytes, dtype: int64
Non-NaN    602
Name: mean_corpuscular_hemoglobin_concentration_mchc, dtype: int64
Non-NaN    602
Name: leukocytes, dtype: int64
Non-NaN    602
Name: basophils, dtype: int64
Non-NaN    602
Name: mean_corpuscular_hemoglobin_mch, dtype: int64
Non-NaN    602
Name: eosinophils, dtype: int64
Non-NaN    602
Name: mean_corpuscular_volume_mcv, dtype: int64
Non-NaN    601
Name: monocytes, dtype: int64
Non-NaN    602
Name: red_blood_cell_distribution_width_rdw, dtype: int64
Non-NaN    208
Name: serum_glucose, dtype: int64
Non-NaN    1354
Name: respiratory_syncytial_virus, dtype: int64
Non-NaN    1354
Name: influenza_a, dtype: int64
Non-NaN    1354
Name: influenza_b, dtype: int64
Non-NaN    1352
Name: parainfluenza_1, dtype: int64
Non-NaN    1352
Name: coronavirusnl63, dtype: int64
Non-NaN    1352
Name: rhinovirus_enterovirus, dtype: int64
Non-NaN    0
Name: mycoplasma_pneumoniae, dtype: int64
Non-NaN    1352
Name: coronavirus_hku1, dtype: int64
Non-NaN    1352
Name: parainfluenza_3, dtype: int64
Non-NaN    1352
Name: chlamydophila_pneumoniae, dtype: int64
Non-NaN    1352
Name: adenovirus, dtype: int64
Non-NaN    1352
Name: parainfluenza_4, dtype: int64
Non-NaN    1352
Name: coronavirus229e, dtype: int64
Non-NaN    1352
Name: coronavirusoc43, dtype: int64
Non-NaN    1352
Name: inf_a_h1n1_2009, dtype: int64
Non-NaN    1352
Name: bordetella_pertussis, dtype: int64
Non-NaN    1352
Name: metapneumovirus, dtype: int64
Non-NaN    1352
Name: parainfluenza_2, dtype: int64
Non-NaN    513
Name: neutrophils, dtype: int64
Non-NaN    397
Name: urea, dtype: int64
Non-NaN    506
Name: proteina_c_reativa_mg_dl, dtype: int64
Non-NaN    424
Name: creatinine, dtype: int64
Non-NaN    371
Name: potassium, dtype: int64
Non-NaN    370
Name: sodium, dtype: int64
Non-NaN    820
Name: influenza_b_rapid_test, dtype: int64
Non-NaN    820
Name: influenza_a_rapid_test, dtype: int64
Non-NaN    225
Name: alanine_transaminase, dtype: int64
Non-NaN    226
Name: aspartate_transaminase, dtype: int64
Non-NaN    153
Name: gamma_glutamyltransferase, dtype: int64
Non-NaN    182
Name: total_bilirubin, dtype: int64
Non-NaN    182
Name: direct_bilirubin, dtype: int64
Non-NaN    182
Name: indirect_bilirubin, dtype: int64
Non-NaN    144
Name: alkaline_phosphatase, dtype: int64
Non-NaN    50
Name: ionized_calcium, dtype: int64
Non-NaN    332
Name: strepto_a, dtype: int64
Non-NaN    40
Name: magnesium, dtype: int64
Non-NaN    136
Name: pco2_venous_blood_gas_analysis, dtype: int64
Non-NaN    136
Name: hb_saturation_venous_blood_gas_analysis, dtype: int64
Non-NaN    136
Name: base_excess_venous_blood_gas_analysis, dtype: int64
Non-NaN    136
Name: po2_venous_blood_gas_analysis, dtype: int64
Non-NaN    1
Name: fio2_venous_blood_gas_analysis, dtype: int64
Non-NaN    136
Name: total_co2_venous_blood_gas_analysis, dtype: int64
Non-NaN    136
Name: ph_venous_blood_gas_analysis, dtype: int64
Non-NaN    136
Name: hco3_venous_blood_gas_analysis, dtype: int64
Non-NaN    97
Name: rods, dtype: int64
Non-NaN    97
Name: segmented, dtype: int64
Non-NaN    97
Name: promyelocytes, dtype: int64
Non-NaN    97
Name: metamyelocytes, dtype: int64
Non-NaN    97
Name: myelocytes, dtype: int64
Non-NaN    97
Name: myeloblasts, dtype: int64
Non-NaN    60
Name: urine_esterase, dtype: int64
Non-NaN    70
Name: urine_aspect, dtype: int64
Non-NaN    70
Name: urine_ph, dtype: int64
Non-NaN    70
Name: urine_hemoglobin, dtype: int64
Non-NaN    70
Name: urine_bile_pigments, dtype: int64
Non-NaN    57
Name: urine_ketone_bodies, dtype: int64
Non-NaN    1
Name: urine_nitrite, dtype: int64
Non-NaN    70
Name: urine_density, dtype: int64
Non-NaN    69
Name: urine_urobilinogen, dtype: int64
Non-NaN    60
Name: urine_protein, dtype: int64
Non-NaN    0
Name: urine_sugar, dtype: int64
Non-NaN    70
Name: urine_leukocytes, dtype: int64
Non-NaN    70
Name: urine_crystals, dtype: int64
Non-NaN    70
Name: urine_red_blood_cells, dtype: int64
Non-NaN    67
Name: urine_hyaline_cylinders, dtype: int64
Non-NaN    69
Name: urine_granular_cylinders, dtype: int64
Non-NaN    70
Name: urine_yeasts, dtype: int64
Non-NaN    70
Name: urine_color, dtype: int64
Non-NaN    0
Name: partial_thromboplastin_time_ptt, dtype: int64
Non-NaN    91
Name: relationship_patient_normal, dtype: int64
Non-NaN    133
Name: international_normalized_ratio_inr, dtype: int64
Non-NaN    101
Name: lactic_dehydrogenase, dtype: int64
Non-NaN    0
Name: prothrombin_time_pt_activity, dtype: int64
Non-NaN    3
Name: vitamin_b12, dtype: int64
Non-NaN    104
Name: creatine_phosphokinase_cpk, dtype: int64
Non-NaN    23
Name: ferritin, dtype: int64
Non-NaN    27
Name: arterial_lactic_acid, dtype: int64
Non-NaN    8
Name: lipase_dosage, dtype: int64
Non-NaN    0
Name: d_dimer, dtype: int64

# Interesting columns to choose.

Research Article: https://www.techscience.com/cmc/v63n1/38464

In [2]:
cols = [
    'patient_age_quantile',
    'hematocrit',
    'hemoglobin',
    'platelets',
    'mean_platelet_volume',
    'red_blood_cells',
    'sars_cov_2_exam_result'
]
rowcol = ['Nrows', 'Ncols']
pd.DataFrame(df.shape, index=rowcol, columns=['Original Data'])

       Original Data
Nrows           5644
Ncols            111

# Separate x and y parameters.

In [3]:
df = df[cols].dropna()
category = [0 if result == 'negative' else 1 for result in df['sars_cov_2_exam_result']]
df['sars_cov_2_exam_result'] = category
X = df.drop('sars_cov_2_exam_result', axis=1)
y = df['sars_cov_2_exam_result'].values.reshape(-1, 1)
pd.DataFrame((X.shape, y.shape), index=['X', 'y'], columns=rowcol)

   Nrows  Ncols
X    599      6
y    599      1

# Separate training and test data.

In [4]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
data = pd.DataFrame({
    'Training': pd.Series(y_train.flatten()).value_counts(),
    'Testing': pd.Series(y_test.flatten()).value_counts()
})
data.index = ['Negative', 'Positive']
data

          Training  Testing
Negative       388      130
Positive        61       20

# Classification

In [5]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(X_train, y_train.flatten())
predictions = classifier.predict(X_test)

In [6]:
results = pd.DataFrame({
    "Actual": y_test.flatten(),
    "Prediction": predictions,
    'Category': np.zeros_like(predictions)
})

results = results.replace(0, 'N')
results = results.replace(1, 'P')

for index, row in results.iterrows():
    if (row['Actual'] == 'N') and (row['Prediction'] == 'N'):
        cat = 'TN'
    if (row['Actual'] == 'P') and (row['Prediction'] == 'P'):
        cat = 'TP'
    if (row['Actual'] == 'N') and (row['Prediction'] == 'P'):
        cat = 'FP'
    if (row['Actual'] == 'P') and (row['Prediction'] == 'N'):
        cat = 'FN'
    results['Category'][index] = cat

# Confusion Matrix

In [7]:
dd = results['Category'].value_counts().to_dict()
cf = ['TP', 'FP', 'TN', 'FN']

for c in cf:
    if c not in dd.keys():
        dd[c] = 0
dd

{'TN': 130, 'FN': 19, 'TP': 1, 'FP': 0}

In [9]:
accuracy = (dd['TP'] + dd['TN']) / data.sum()['Testing']
precision = (dd['TP']) / (dd['TP'] + dd['FP'])
recall = (dd['TP']) / (dd['TP'] + dd['FN'])

pd.DataFrame([accuracy, precision, recall],
             index=['Accuracy', 'Precision', 'Recall'],
             columns=['Percent']
            )

            Percent
Accuracy   0.873333
Precision  1.000000
Recall     0.050000